apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  labels:
    pipelines.openshift.io/runtime: generic
    pipelines.openshift.io/strategy: docker
    pipelines.openshift.io/used-by: build-cloud
  name: docker-build-tssc
spec:
  params:
    - description: Source Repository URL
      name: git-url
      type: string
    - default: ""
      description: Revision of the Source Repository
      name: revision
      type: string
    - description: Fully Qualified Output Image
      name: output-image
      type: string
    - default: .
      description: Path to the source code of an application's component from where to build image.
      name: path-context
      type: string
    - default: Dockerfile
      description: Path to the Dockerfile inside the context specified by parameter path-context
      name: dockerfile
      type: string
    - default: "false"
      description: Force rebuild image
      name: rebuild
      type: string
    - default: ""
      description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
      name: image-expires-after
      type: string
    - default: rox-api-token
      name: stackrox-secret
      type: string
    - default: gitops-auth-secret
      description: 'Secret name to enable this pipeline to update the gitops repo with the new image. '
      name: gitops-auth-secret-name
      type: string
    - default: tpa-secret
      description: The name of the Secret that contains Trustification (TPA) configuration
      name: trustification-secret-name
    - default: cosign-pub
      description: 'Secret name to enable verify cosign signature. '
      name: cosign-public-key-secret
      type: string
    - default: push
      description: Event that triggered the pipeline run, e.g. push, pull_request
      name: event-type
      type: string
    - default: []
      description: Array of --build-arg values ("arg=value" strings) for buildah
      name: build-args
      type: array
    - default: ""
      description: Path to a file with build arguments for buildah, see https://www.mankier.com/1/buildah-build#--build-arg-file
      name: build-args-file
      type: string
  results:
    - name: IMAGE_DIGEST
      description: Digest of the image just built
      value: $(tasks.build.results.IMAGE_DIGEST)
    - name: IMAGE_URL
      description: Image repository and tag where the built image was pushed
      value: $(tasks.build.results.IMAGE_URL)
    - name: BASE_IMAGES_DIGESTS
      description: Digests of the base images used for build
      value: $(tasks.build.results.BASE_IMAGES_DIGESTS)
    - name: SBOM_BLOB_URL
      description: Link to the SBOM layer pushed to the registry
      value: $(tasks.build.results.SBOM_BLOB_URL)
    - name: CHAINS-GIT_URL
      value: $(tasks.clone-repository.results.url)
    - name: CHAINS-GIT_COMMIT
      value: $(tasks.clone-repository.results.commit)
    - name: ACS_SCAN_OUTPUT
      value: $(tasks.scan.results.SCAN_OUTPUT)
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.revision)
        - name: depth
          value: "0"
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
        - name: basic-auth
          workspace: git-auth
    - name: build
      params:
        - name: rox-secret-name
          value: $(params.stackrox-secret)
        - name: gitops-secret-name
          value: $(params.gitops-auth-secret-name)
        - name: cosign-public-secret-name
          value: $(params.cosign-public-key-secret)
        - name: tpa_secret_name
          value: $(params.trustification-secret-name)
        - name: IMAGE
          value: $(params.output-image)
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: CONTEXT
          value: $(params.path-context)
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)
        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)
        - name: BUILD_ARGS
          value:
            - $(params.build-args[*])
        - name: BUILD_ARGS_FILE
          value: $(params.build-args-file)
      runAfter:
        - clone-repository
      taskRef:
        name: build-workload
      workspaces:
        - name: source
          workspace: workspace
    - name: deploy
      params:
        - name: gitops-secret-name
          value: $(params.gitops-auth-secret-name)
        - name: IMAGE
          value: $(params.output-image)
        - name: CONTEXT
          value: $(params.path-context)
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)
        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)
      runAfter:
        - build
      taskRef:
        name: deploy-workload
      when:
        - input: $(params.event-type)
          operator: notin
          values:
            - pull_request
            - Merge Request
      workspaces:
        - name: source
          workspace: workspace
    - name: deployment-check
      params:
        - name: rox-secret-name
          value: $(params.stackrox-secret)
        - name: gitops-secret-name
          value: $(params.gitops-auth-secret-name)
        - name: IMAGE
          value: $(params.output-image)
        - name: CONTEXT
          value: $(params.path-context)
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)
        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)
      runAfter:
        - deploy
      taskRef:
        name: deploy-workload-check
      when:
        - input: $(params.event-type)
          operator: in
          values:
            - push
            - Push
      workspaces:
        - name: source
          workspace: workspace
    - name: scan
      params:
        - name: rox-secret-name
          value: $(params.stackrox-secret)
        - name: IMAGE
          value: $(params.output-image)
        - name: CONTEXT
          value: $(params.path-context)
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)
        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)
      runAfter:
        - build
      taskRef:
        name: scan-workload
      workspaces:
        - name: source
          workspace: workspace
    - name: show-sbom
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: CONTEXT
          value: $(params.path-context)
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)
        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)
      runAfter:
        - deploy
        - scan
      taskRef:
        name: show-workload-sbom
      workspaces:
        - name: source
          workspace: workspace
    - name: summarize
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: CONTEXT
          value: $(params.path-context)
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)
        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)
      runAfter:
        - deploy
        - scan
      taskRef:
        name: summarize-workload
      workspaces:
        - name: source
          workspace: workspace
  workspaces:
    - name: workspace
    - name: git-auth
      optional: true
