apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: ${{ values.name }}
  app.kubernetes.io/managed-by: agent-office
  agentoffice.ai/agent: ${{ values.name }}
  backstage.io/kubernetes-id: ${{ values.name }}
resources:
  - agentworkstation.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
