apiVersion: v1
kind: Secret
metadata:
  name: agent-${{ values.name }}-secret
  namespace: ${{ values.namespace }}
type: Opaque
stringData:
{%- if values.provider == "smr" %}
  SMR_API_KEY: "${{ values.apiKey }}"
{%- elif values.provider == "openai" %}
  OPENAI_API_KEY: "${{ values.apiKey }}"
{%- elif values.provider == "anthropic" %}
  ANTHROPIC_API_KEY: "${{ values.apiKey }}"
{%- endif %}
