---
name: Checks

"on":
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  generated-file-freshness:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install node dependencies
        run: |
          make install-deps

      - name: Confirm file freshness
        run: |
          make ensure-fresh

  script-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install shfmt
        run: |
          make install-shfmt

      - name: Confirm script formatting
        run: |
          make ensure-formatted

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint YAML files
        run: yamllint generated/ templates/data.yaml

  bats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: tools/syft/go.mod

      - name: Run tests
        run: make test
        with:
          submodules: 'true'
